language: java
jdk:
  - oraclejdk8
  - oraclejdk9
  - openjdk8
script: mvn package
deploy:
  on:
    tags: true
    jdk: oraclejdk8
  before_deploy: "mv target/*.jar scrapt.jar"
  provider: releases
  api_key:
    secure: "TODO"
    file: "scrapt.jar"
    skip_cleanup: true
